#!/usr/bin/env bash
#
# install.sh — install/convert the agents-factory roster, skills, commands, and
# framework docs for a target platform.
#
# Source of truth: .github/{agents,skills,commands} plus process/ and templates/. This
# script DERIVES every other layout from them; never hand-edit a derived folder
# (.claude/, .cursor/, or the repo-root agents/ skills/ commands/) — re-run this instead.
#
# Installs GLOBALLY by default (user-level config: ~/.claude, ~/.cursor, ~/.copilot, …).
# Pass --scope project --path <dir> to install into a specific project instead.
#
# Portability: bash 3.2+ (macOS default), BSD and GNU userland. No GNU-only flags.
#
set -euo pipefail

if [[ -z "${BASH_VERSINFO:-}" || "${BASH_VERSINFO[0]}" -lt 3 ]]; then
  echo "error: this script requires bash 3.2 or newer." >&2
  exit 1
fi

# die() may run inside a command substitution, where `exit` would only leave the
# subshell. Signal the main shell so a fatal error is fatal everywhere.
MAIN_PID=$$
trap 'exit 1' TERM

TARGET="claude"
SCOPE=""
DEST=""
DRY_RUN=false
CHECK=false
KEEP_EXISTING=false
FORCE=false
# CDPATH would make `cd` print the directory and corrupt the captured path.
ROOT="$(CDPATH='' cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"

VALID_TARGETS="claude cursor copilot codex hermes agents roo zoo docs plugin repo"
VALID_SCOPES="global project"
GENERATED_BY="agents-factory: generated by scripts/install.sh"

usage() {
  cat <<'EOF'
install.sh — install/convert the agents-factory roster + skills + commands + framework docs.

Usage:
  scripts/install.sh --target claude                            # global  -> ~/.claude
  scripts/install.sh --target claude --scope project --path DIR # project -> DIR/.claude
  scripts/install.sh --target cursor                            # global  -> ~/.cursor/rules
  scripts/install.sh --target copilot                           # global  -> ~/.copilot (agents+skills)
  scripts/install.sh --target codex                             # global  -> ~/.codex/skills (agents shipped as skills)
  scripts/install.sh --target hermes                            # global  -> ~/.hermes/skills (agents shipped as skills)
  scripts/install.sh --target agents                            # global  -> ~/.agents (generic per-agent custom-mode files)
  scripts/install.sh --target roo                               # global  -> Zoo/Roo custom_modes.yaml (editor globalStorage)
  scripts/install.sh --target roo --scope project --path DIR    # project -> DIR/.roomodes (native single-file format)
  scripts/install.sh --target docs                              # global  -> ~/.agents-factory (process/ + templates/ only)
  scripts/install.sh --target docs --scope project --path DIR   # project -> DIR/.agents-factory (e.g. for plugin users)
  scripts/install.sh --target plugin                            # regenerate this repo's plugin dirs
  scripts/install.sh --target repo                              # regenerate EVERY derived dir in this repo
  scripts/install.sh --target repo --dry-run                    # show what would change; write nothing
  scripts/install.sh --target repo --check                      # CI gate: exit 1 if anything is stale

Flags:
  --target  claude | cursor | copilot | codex | hermes | agents | roo | zoo | docs | plugin | repo
            (default: claude)
            ('roo' and 'zoo' are aliases — same .roomodes / custom_modes.yaml format;
             global installs auto-detect Zoo Code and legacy Roo Code storage)
            ('codex' and 'hermes' have no per-agent definition format: each agent is
             shipped AS a skill, with its tool posture carried as prose)
  --scope   global | project                                     (default: global)
  --path    DIR    project root (required when --scope project)
  --dest    DIR    alias for "--scope project --path DIR" (back-compat)
  --dry-run        report what would be created/updated; make no changes
  --check          --dry-run plus a non-zero exit when anything is stale, orphaned,
                   or warned about. For CI: `scripts/install.sh --target repo --check`
  --keep-existing  never overwrite a skill or command already at the destination
                   (cannot be combined with --check)
  --force          overwrite a Zoo/Roo modes file this script did not generate
                   (the previous file is kept as <file>.bak)
  -h, --help       this message

Framework docs:
  Every agent cites process/*.md and templates/*.md. Platform targets also install those
  docs: globally to $AGENTS_FACTORY_HOME (default ~/.agents-factory), per project to
  <DIR>/.agents-factory. Agents resolve them from the project root first, then
  <project>/.agents-factory, then $AGENTS_FACTORY_HOME.

Targets in brief:
  repo     the one to run after editing anything in .github/. Regenerates the plugin
           component dirs, .claude/, and .cursor/ in this repository, in one pass.
  plugin   only the repo-root agents/ skills/ commands/ that .claude-plugin/ discovers.
  docs     only process/ + templates/ — what a plugin install needs next to it.
EOF
}

die() {
  echo "error: $*" >&2
  kill -s TERM "$MAIN_PID" 2>/dev/null || true
  exit 1
}

in_list() { # in_list <needle> <space-separated haystack> — exact single-word match
  case "$1" in ""|*[[:space:]]*) return 1 ;; esac
  case " $2 " in *" $1 "*) return 0 ;; *) return 1 ;; esac
}

need_arg() { # need_arg <flag> <value-or-empty>
  [[ -n "${2:-}" ]] || { echo "error: $1 requires a value" >&2; usage >&2; exit 1; }
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --target)  need_arg --target "${2:-}"; TARGET="$2"; shift 2 ;;
    --scope)   need_arg --scope  "${2:-}"; SCOPE="$2";  shift 2 ;;
    --path)    need_arg --path   "${2:-}"; DEST="$2";   shift 2 ;;
    --dest)    need_arg --dest   "${2:-}"; DEST="$2"; SCOPE="${SCOPE:-project}"; shift 2 ;;
    --dry-run) DRY_RUN=true; shift ;;
    --check)   DRY_RUN=true; CHECK=true; shift ;;
    --keep-existing) KEEP_EXISTING=true; shift ;;
    --force)   FORCE=true; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown argument: $1" >&2; usage >&2; exit 1 ;;
  esac
done

in_list "$TARGET" "$VALID_TARGETS" \
  || die "unknown target: '$TARGET' (use ${VALID_TARGETS// / | })"
[[ -z "$SCOPE" ]] || in_list "$SCOPE" "$VALID_SCOPES" \
  || die "unknown scope: '$SCOPE' (use ${VALID_SCOPES// / | })"
if $CHECK && $KEEP_EXISTING; then
  die "--check cannot be combined with --keep-existing (kept files would never be compared)"
fi

# --- Resolve install scope -> DEST base directory ------------------------------
# The conversion functions append the platform subdir (e.g. .claude/agents) to DEST:
#   global  -> DEST=$HOME    => ~/.claude/agents, ~/.cursor/rules
#   project -> DEST=<path>   => <path>/.claude/agents, <path>/.cursor/rules
case "$TARGET" in
  plugin|repo)
    # These write into THIS repository: the plugin components must sit at the repo root
    # next to .claude-plugin/, and `repo` regenerates the repo's own derived dirs.
    if [[ -n "$DEST" && "$(CDPATH='' cd -- "$DEST" 2>/dev/null && pwd)" != "$ROOT" ]]; then
      die "--target $TARGET always writes to this repository ($ROOT); --path/--dest is not applicable"
    fi
    [[ "${SCOPE:-}" != "global" ]] || echo "note: --scope is ignored for --target $TARGET." >&2
    DEST="$ROOT"; SCOPE="project"
    ;;
  *)
    if [[ -z "$SCOPE" ]]; then
      if [[ -n "$DEST" ]]; then SCOPE="project"; else SCOPE="global"; fi
    fi
    case "$SCOPE" in
      global)
        [[ -z "$DEST" ]] || die "--scope global installs to \$HOME; drop --path/--dest, or pass --scope project"
        [[ -n "${HOME:-}" ]] || die "\$HOME is not set"
        DEST="$HOME"
        ;;
      project)
        [[ -n "$DEST" ]] || die "--scope project requires --path <dir>"
        # Resolve to an absolute path so guards that compare against $ROOT are reliable
        # ("--path ." must be recognised as this repository).
        [[ -d "$DEST" ]] || die "--path '$DEST' is not a directory"
        DEST="$(CDPATH='' cd -- "$DEST" && pwd)"
        ;;
    esac
    ;;
esac

AGENTS_SRC="$ROOT/.github/agents"
SKILLS_SRC="$ROOT/.github/skills"
COMMANDS_SRC="$ROOT/.github/commands"
DOCS_DIRS="process templates"
[[ -d "$AGENTS_SRC" ]] || die "$AGENTS_SRC not found — run from the repo."

# Where the framework docs land, and the path agents are told to look in.
AF_HOME_DEFAULT="$HOME/.agents-factory"
AF_HOME="${AGENTS_FACTORY_HOME:-$AF_HOME_DEFAULT}"

# --- Change accounting ---------------------------------------------------------
WROTE=0; UNCHANGED=0; SKIPPED=0; WOULD=0; ORPHANS=0
# Warnings are often raised inside $(...) subshells, where a counter increment would be
# lost. Record them in a file so the summary and --check see every one.
WARN_FILE="$(mktemp "${TMPDIR:-/tmp}/agents-factory-warn.XXXXXX")"
trap 'rm -f "$WARN_FILE"' EXIT

warn() { echo "  WARNING: $*" >&2; echo "$*" >> "$WARN_FILE"; }
warning_count() { awk 'END{print NR}' "$WARN_FILE"; }

# Every path this run generates (or would generate), for manifest-based orphan detection.
GENERATED_LIST="$(mktemp "${TMPDIR:-/tmp}/agents-factory-gen.XXXXXX")"
trap 'rm -f "$WARN_FILE" "$GENERATED_LIST"' EXIT
note_generated() { printf '%s\n' "$1" >> "$GENERATED_LIST"; }

# localize <content> — in installs outside this repo, point agents at the actual docs
# home when $AGENTS_FACTORY_HOME moved it from the default.
localize() {
  local s="$1"
  if [[ "$DEST" != "$ROOT" && "$AF_HOME" != "$AF_HOME_DEFAULT" ]]; then
    s="${s//\~\/.agents-factory/$AF_HOME}"
  fi
  printf '%s' "$s"
}

# emit <dest> <content> — write only when the content differs; honours --dry-run.
emit() {
  local dest="$1" content
  content="$(localize "$2")"
  note_generated "$dest"
  if [[ -f "$dest" ]] && [[ "$(cat "$dest")" == "$content" ]]; then
    UNCHANGED=$((UNCHANGED+1)); return 0
  fi
  if $DRY_RUN; then
    if [[ -f "$dest" ]]; then echo "  would update  $dest"; else echo "  would create  $dest"; fi
    WOULD=$((WOULD+1)); return 0
  fi
  mkdir -p "$(dirname "$dest")"
  printf '%s\n' "$content" > "$dest"
  WROTE=$((WROTE+1))
}

# sync_dir <src_dir> <dst_dir> <label> — mirror a directory (skills, docs). Refuses to
# replace a destination that is not recognisably the same kind of thing.
sync_dir() {
  local src="$1" dst="$2" label="$3" marker="$4"
  note_generated "$dst"
  if [[ -e "$dst" && ! -d "$dst" ]]; then
    die "refusing to replace '$dst' — it is not a directory"
  fi
  if [[ -d "$dst" ]] && [[ -n "$marker" ]] && [[ ! -e "$dst/$marker" ]]; then
    die "refusing to replace '$dst' — not a $label (no $marker)"
  fi
  if [[ -d "$dst" ]] && diff -rq "$src" "$dst" >/dev/null 2>&1; then
    UNCHANGED=$((UNCHANGED+1)); return 0
  fi
  if $DRY_RUN; then
    if [[ -e "$dst" ]]; then echo "  would update  $label -> $dst"; else echo "  would create  $label -> $dst"; fi
    WOULD=$((WOULD+1)); return 0
  fi
  mkdir -p "$(dirname "$dst")"
  [[ ! -e "$dst" ]] || rm -rf -- "$dst"
  cp -R "$src" "$dst"; WROTE=$((WROTE+1)); echo "  $label -> $dst"
}

# --- Orphans -------------------------------------------------------------------
# Two regimes:
#  * owned dirs (this repo's derived trees): every entry must correspond to a source,
#    so anything unexpected is an orphan;
#  * shared dirs (~/.claude/agents, a project's .codex/skills, …): the user's own files
#    live there too. Only paths a PREVIOUS run of this script recorded in its manifest
#    can be orphans — user files are never flagged.
report_owned_orphans() { # report_owned_orphans <dir> <glob-suffix>
  local dir="$1" suffix="$2" f
  [[ -d "$dir" ]] || return 0
  for f in "$dir"/*"$suffix"; do
    [[ -e "$f" ]] || continue
    f="${f%/}"
    if ! grep -qxF "$f" "$GENERATED_LIST"; then
      echo "  ORPHAN: $f has no source (rename or delete it)"
      ORPHANS=$((ORPHANS+1))
    fi
  done
}

MANIFEST=""   # set per target: the file recording what this script installed there

report_manifest_orphans() {
  local p
  [[ -n "$MANIFEST" && -f "$MANIFEST" ]] || return 0
  while IFS= read -r p || [[ -n "$p" ]]; do
    [[ -n "$p" && "$p" != \#* ]] || continue
    [[ -e "$p" ]] || continue
    if ! grep -qxF "$p" "$GENERATED_LIST"; then
      echo "  ORPHAN: $p was installed by an earlier run but has no source now (delete it)"
      ORPHANS=$((ORPHANS+1))
    fi
  done < "$MANIFEST"
}

write_manifest() {
  [[ -n "$MANIFEST" ]] || return 0
  $DRY_RUN && return 0
  mkdir -p "$(dirname "$MANIFEST")"
  {
    echo "# $GENERATED_BY — paths installed by the last run; used to detect orphans."
    sort -u "$GENERATED_LIST"
  } > "$MANIFEST"
}

# --- Frontmatter parsing -------------------------------------------------------
# All parsing is scoped to the leading ---/--- block, tolerates CRLF line endings, and
# never fails a pipeline under `set -o pipefail` when a key is absent.

# frontmatter <file> — the raw frontmatter lines (CR stripped), or nothing.
frontmatter() {
  awk 'NR==1 { sub(/\r$/, ""); if ($0 != "---") exit; next }
       { sub(/\r$/, "") }
       $0 == "---" { exit }
       { print }' "$1"
}

# yaml_unquote <scalar> — strip one level of YAML quoting.
yaml_unquote() {
  local v="$1"
  if [[ ${#v} -ge 2 && "$v" == \"*\" ]]; then
    v="${v:1:${#v}-2}"; v="${v//\\\"/\"}"; v="${v//\\\\/\\}"
  elif [[ ${#v} -ge 2 && "$v" == \'*\' ]]; then
    v="${v:1:${#v}-2}"; v="${v//\'\'/\'}"
  fi
  printf '%s' "$v"
}

# field_value <file> <key> — a top-level scalar from the frontmatter, unquoted. Folded
# (>, >-) and literal (|, |-) block scalars are joined into one line.
field_value() {
  local raw
  # The awk readers below never `exit` early: under pipefail an early exit can SIGPIPE
  # the writer and fail the whole substitution.
  raw="$(frontmatter "$1" | awk -v k="$2" '
    found == 0 && index($0, k ":") == 1 {
      v = substr($0, length(k) + 2); sub(/^[ \t]+/, "", v); sub(/[ \t]+$/, "", v)
      if (v ~ /^[>|][-+]?$/) { found = 2; out = ""; next }
      out = v; found = 3; next
    }
    found == 2 {
      if ($0 ~ /^[ \t]/ || $0 == "") { line = $0; sub(/^[ \t]+/, "", line)
        if (line != "") out = (out == "" ? line : out " " line); next }
      found = 3
    }
    END { if (found >= 2) print out }')"
  yaml_unquote "$raw"
}

# tool_ids <file> — tool ids from the frontmatter `tools:` key, in source order. Accepts
# a flow list with double, single, or no quotes, or a block sequence. Dies on anything
# else rather than silently degrading an agent to read-only.
tool_ids() {
  local src="$1" fm value rest
  fm="$(frontmatter "$src")"
  if ! printf '%s\n' "$fm" | grep -q '^tools:'; then
    die "$src: frontmatter has no tools: key"
  fi
  value="$(printf '%s\n' "$fm" | awk '!done && /^tools:/ { v = $0; sub(/^tools:[ \t]*/, "", v); print v; done = 1 }')"
  if [[ -z "$value" ]]; then
    # block sequence: following "  - id" lines
    rest="$(printf '%s\n' "$fm" | awk '
      started == 1 && /^[ \t]+-[ \t]*/ { v = $0; sub(/^[ \t]+-[ \t]*/, "", v); print v; next }
      started == 1 { started = 2 }
      started == 0 && /^tools:[ \t]*$/ { started = 1 }')"
    [[ -n "$rest" ]] || die "$src: tools: is empty"
    printf '%s\n' "$rest" | tr -d "\"'" | awk 'NF { print $1 }'
    return
  fi
  case "$value" in
    \[*\]) ;;
    *) die "$src: cannot parse tools: '$value' (use a list, e.g. [\"read\",\"search\"])" ;;
  esac
  printf '%s\n' "$value" | tr -d "[]\"'" | tr ',' '\n' | awk 'NF { print $1 }'
}

# is_tools_continuation <line> — a block-sequence item belonging to `tools:`.
is_seq_item() { [[ "$1" =~ ^[[:space:]]+-[[:space:]]* ]]; }

# body_of <file> — everything after the closing frontmatter delimiter, CR stripped,
# leading blank lines dropped. A `---` inside the body (a horizontal rule, a YAML
# example) is content and is kept.
body_of() {
  awk 'NR==1 { sub(/\r$/, ""); if ($0 == "---") { fm = 1; next } else { fm = 2 } }
       { sub(/\r$/, "") }
       fm == 1 { if ($0 == "---") fm = 2; next }
       !started { if ($0 ~ /^[ \t]*$/) next; started = 1 }
       { print }' "$1"
}

# indent_block <n> — indent non-blank stdin lines by n spaces (blank lines stay empty).
indent_block() {
  awk -v n="$1" 'BEGIN { pad = sprintf("%" n "s", "") } /^[ \t]*$/ { print ""; next } { print pad $0 }'
}

# yaml_dq <string> — a double-quoted YAML scalar (escapes backslash and quote).
yaml_dq() {
  local s="$1"
  s="${s//\\/\\\\}"; s="${s//\"/\\\"}"
  printf '"%s"' "$s"
}

# persona_of <file> — the "You are …" paragraph of the body.
persona_of() {
  body_of "$1" | awk 'done { next }
                      !cap { if ($0 ~ /^You are/) cap = 1; else next }
                      /^[ \t]*$/ { done = 1; next }
                      { print }'
}

# --- Tool ids -> platform tools / posture --------------------------------------
map_tool_id() { # VS Code tool id -> Claude Code tool name(s)
  case "$1" in
    read)      echo "Read" ;;
    search)    echo "Grep Glob" ;;
    edit)      echo "Edit Write" ;;
    execute)   echo "Bash" ;;
    todo)      echo "TodoWrite" ;;
    agent)     echo "Task" ;;
    web|fetch) echo "WebFetch WebSearch" ;;
    vscode)    echo "" ;;       # editor-specific; no Claude equivalent, dropped on purpose
    *)         return 1 ;;      # unknown id — caller warns
  esac
}

# posture_code <file> — collapse the tool ids to the roster posture token.
# Matches the legend in process/agent-roster.md: R, R+route, E, E+T, O.
posture_code() {
  local id has_edit=0 has_exec=0 has_agent=0 has_todo=0
  for id in $(tool_ids "$1"); do
    case "$id" in
      edit)    has_edit=1 ;;
      execute) has_exec=1 ;;
      agent)   has_agent=1 ;;
      todo)    has_todo=1 ;;
    esac
  done
  if   [[ $has_agent -eq 1 && $has_edit -eq 0 && $has_todo -eq 1 ]]; then echo "O"
  elif [[ $has_agent -eq 1 && $has_edit -eq 0 ]];                   then echo "R+route"
  elif [[ $has_exec  -eq 1 && $has_edit -eq 1 ]];                   then echo "E+T"
  elif [[ $has_edit  -eq 1 ]];                                      then echo "E"
  else                                                                   echo "R"
  fi
}

# claude_tools_line <file> — "tools: A, B, C" (deduped, source order).
# R+route drops `agent`: a Claude Code subagent cannot start another subagent, so the
# Code Reviewer's routing is a recommendation the /run-delivery main loop dispatches.
claude_tools_line() {
  local src="$1" label id mapped t out="" seen=" " code
  label="$(basename "$src" .agent.md)"
  code="$(posture_code "$src")"
  for id in $(tool_ids "$src"); do
    [[ "$code" == "R+route" && "$id" == "agent" ]] && continue
    if ! mapped="$(map_tool_id "$id")"; then
      warn "$label: unknown tool id '$id' — dropped (add it to map_tool_id)."
      continue
    fi
    for t in $mapped; do
      case "$seen" in *" $t "*) continue ;; esac
      seen="$seen$t "; out="$out, $t"
    done
  done
  [[ -n "$out" ]] || { warn "$label: no tool maps to Claude Code — granting Read only."; out=", Read"; }
  echo "tools: ${out#, }"
}

# --- Tool posture as prose -----------------------------------------------------
# Several targets cannot carry a tool grant at all (Cursor rules, Codex and Hermes
# skills). There the posture survives only as an instruction, so it must at least be
# stated — an unstated posture is the one that gets violated.
posture_note() { # posture_note <code>
  case "$1" in
    R)       echo "Read and search only. Never edit a file, never run a command." ;;
    R+route) echo "Read and search only, plus recommending or routing to another agent. Never edit a file, never run a command." ;;
    E)       echo "Read, search, and edit files inside your ownership boundary — as narrowed by the Scope & Boundaries section below, which is the binding limit. Never run shell commands." ;;
    E+T)     echo "Read, search, edit inside your ownership boundary — as narrowed by the Scope & Boundaries section below, which is the binding limit — and run commands. Destructive or irreversible commands still need explicit human approval." ;;
    O)       echo "Read, search, track tasks, and dispatch other agents. Never edit product files yourself." ;;
  esac
}

posture_enforcement() { # posture_enforcement <platform> <code>
  case "$1" in
    codex)
      case "$2" in
        R|R+route) echo 'Codex grants tools per session, not per skill — run read-only work with `codex --sandbox read-only`.' ;;
        *)         echo 'Codex grants tools per session, not per skill — `--sandbox workspace-write --ask-for-approval on-request` matches this posture; the boundary above is yours to hold.' ;;
      esac
      ;;
    hermes)
      case "$2" in
        R|R+route) echo 'Hermes grants toolsets per session, not per skill — run read-only work with `hermes --safe-mode`.' ;;
        *)         echo 'Hermes grants toolsets per session, not per skill — the ownership boundary above is yours to hold; approve destructive commands explicitly.' ;;
      esac
      ;;
    cursor)
      case "$2" in
        R|R+route) echo 'Cursor rules carry no tool grant — this posture is an instruction, not a sandbox. Keep the model read-only by reviewing, not applying, its proposed edits.' ;;
        *)         echo 'Cursor rules carry no tool grant — this posture is an instruction, not a sandbox. The ownership boundary above is what keeps the edits in scope.' ;;
      esac
      ;;
  esac
}

# --- Skills, commands, docs ----------------------------------------------------
install_skills() {
  local skills_dir="$1" s name dst
  [[ -d "$SKILLS_SRC" ]] || return 0
  for s in "$SKILLS_SRC"/*/; do
    [[ -d "$s" ]] || continue
    name="$(basename "$s")"; dst="$skills_dir/$name"
    if [[ -e "$dst" ]] && $KEEP_EXISTING; then
      note_generated "$dst"
      echo "  skill '$name' kept (--keep-existing)"; SKIPPED=$((SKIPPED+1)); continue
    fi
    sync_dir "${s%/}" "$dst" "skill '$name'" "SKILL.md"
  done
}

install_commands() {
  local cmd_dir="$1" c name dst
  [[ -d "$COMMANDS_SRC" ]] || return 0
  for c in "$COMMANDS_SRC"/*.md; do
    [[ -e "$c" ]] || continue
    name="$(basename "$c")"; dst="$cmd_dir/$name"
    if [[ -f "$dst" ]] && $KEEP_EXISTING; then
      note_generated "$dst"
      echo "  command '$name' kept (--keep-existing)"; SKIPPED=$((SKIPPED+1)); continue
    fi
    emit "$dst" "$(cat "$c")"
  done
}

# install_docs <base> — process/ and templates/ under <base>, where agents look for them.
install_docs() {
  local base="$1" d
  # The repository already has process/ and templates/ at its root.
  [[ "$base" != "$ROOT" && "$DEST" != "$ROOT" ]] || return 0
  for d in $DOCS_DIRS; do
    sync_dir "$ROOT/$d" "$base/$d" "framework docs $d/" ""
  done
  emit "$base/README.md" "$(docs_readme)"
}

docs_readme() {
  cat <<EOF
# agents-factory framework docs

$GENERATED_BY from process/ and templates/ — do not edit; re-run the installer.

Agents and commands cite \`process/…\` and \`templates/…\`. They resolve those paths from
the project root first, then \`<project>/.agents-factory/\`, then this directory.
EOF
}

# platform_docs — where a platform target installs the docs for its scope.
platform_docs_base() {
  if [[ "$SCOPE" == "global" ]]; then echo "$AF_HOME"; else echo "$DEST/.agents-factory"; fi
}

# A skill is just Markdown, so a platform with no skills runtime can still use one —
# provided something tells the model the skill exists. These two helpers are that
# something: an index for file-loading harnesses, and native rules for Cursor.

# write_skills_index <skills_dir> <how-to-invoke sentence>
write_skills_index() {
  local dir="$1" howto="$2" s name desc content
  [[ -d "$SKILLS_SRC" ]] || return 0
  content="$(
    echo "# Skills index"
    echo
    echo "Generated by \`scripts/install.sh\` from \`.github/skills/\` — do not edit."
    echo
    echo "This platform has no skills runtime. $howto"
    echo
    echo "| Skill | Use it when | Path |"
    echo "|---|---|---|"
    for s in "$SKILLS_SRC"/*/; do
      [[ -d "$s" ]] || continue
      name="$(basename "$s")"
      desc="$(field_value "$s/SKILL.md" description)"
      printf '| `%s` | %s | `%s/SKILL.md` |\n' "$name" "${desc//|/\\|}" "$name"
    done
  )"
  emit "$dir/SKILLS-INDEX.md" "$content"
}

# gen_skill_rules <out_rules_dir> — each skill as a Cursor rule, so it is @-mentionable
# the way the agents are. Companion reference files stay on disk under .cursor/skills/.
gen_skill_rules() {
  local out_dir="$1" s f name desc extras content count=0
  [[ -d "$SKILLS_SRC" ]] || return 0
  for s in "$SKILLS_SRC"/*/; do
    [[ -d "$s" ]] || continue
    name="$(basename "$s")"
    desc="$(field_value "$s/SKILL.md" description)"
    extras=""
    for f in "$s"*; do
      [[ -e "$f" && "$(basename "$f")" != "SKILL.md" ]] || continue
      extras="$extras$(basename "$f")"$'\n'
    done
    content="$(
      echo "---"
      echo "description: $(yaml_dq "$desc")"
      echo "alwaysApply: false"
      echo "---"
      echo
      body_of "$s/SKILL.md"
      if [[ -n "$extras" ]]; then
        echo
        echo "---"
        echo
        echo "Companion files for this skill (read them when the steps above reference them):"
        echo
        printf '%s' "$extras" | sed "s|^|- \`.cursor/skills/$name/|; s|$|\`|"
      fi
    )"
    emit "$out_dir/skill-$name.mdc" "$content"
    count=$((count+1))
  done
  echo "  $count skills -> $out_dir/skill-*.mdc (@-mentionable)"
}

# --- Agents --------------------------------------------------------------------
# Convert .github/agents/*.agent.md into Claude-format *.md in <out_dir>.
# The tools:/argument-hint: transform is scoped to the YAML frontmatter block, so a body
# line that happens to start with one of those words is passed through untouched.
gen_agents() {
  local out_dir="$1"
  local count=0 src base dest line body fm skipping
  for src in "$AGENTS_SRC"/*.agent.md; do
    [[ -e "$src" ]] || continue
    base="$(basename "$src" .agent.md)"
    dest="$out_dir/$base.md"
    body=""; fm=0; skipping=false
    while IFS= read -r line || [[ -n "$line" ]]; do
      line="${line%$'\r'}"
      if [[ "$fm" -lt 2 && "$line" == "---" ]]; then
        fm=$((fm+1)); body="$body$line"$'\n'; continue
      fi
      if [[ "$fm" -eq 1 ]]; then
        if $skipping && is_seq_item "$line"; then continue; fi
        skipping=false
        if [[ "$line" == tools:* ]]; then
          body="$body$(claude_tools_line "$src")"$'\n'; skipping=true; continue
        elif [[ "$line" == argument-hint:* ]]; then
          continue                                 # Claude subagents have no argument-hint
        fi
      fi
      body="$body$line"$'\n'
    done < "$src"
    emit "$dest" "${body%$'\n'}"
    count=$((count+1))
  done
  echo "  $count agents -> $out_dir/"
}

convert_claude() {
  gen_agents "$DEST/.claude/agents"
  install_skills "$DEST/.claude/skills"
  install_commands "$DEST/.claude/commands"
  if [[ "$DEST" == "$ROOT" ]]; then
    report_owned_orphans "$DEST/.claude/agents" ".md"
    report_owned_orphans "$DEST/.claude/skills" "/"
    report_owned_orphans "$DEST/.claude/commands" ".md"
  else
    install_docs "$(platform_docs_base)"
    MANIFEST="$DEST/.claude/.agents-factory-manifest"
  fi
  echo "Done. Start a delivery run with:  /run-delivery <run-id>   or an advisory review with:  /run-advisory \"<topic>\""
}

# Claude Code marketplace plugin: components live at repo root (agents/ skills/
# commands/) so the .claude-plugin/ manifest can auto-discover them. The two manifests
# (.claude-plugin/plugin.json + marketplace.json) are tracked, not generated.
convert_plugin() {
  gen_agents "$DEST/agents"
  install_skills "$DEST/skills"
  install_commands "$DEST/commands"
  report_owned_orphans "$DEST/agents" ".md"
  report_owned_orphans "$DEST/skills" "/"
  report_owned_orphans "$DEST/commands" ".md"
  if [[ -f "$DEST/.claude-plugin/plugin.json" ]]; then
    echo "  manifest present -> $DEST/.claude-plugin/plugin.json"
  else
    die "$DEST/.claude-plugin/plugin.json missing — the plugin would not load."
  fi
  echo "Done. Local test:  /plugin marketplace add $DEST"
  echo "Plugin users also need the framework docs:  scripts/install.sh --target docs"
}

convert_cursor() {
  local out_dir="$DEST/.cursor/rules"
  local count=0 src base dest desc code content
  for src in "$AGENTS_SRC"/*.agent.md; do
    [[ -e "$src" ]] || continue
    base="$(basename "$src" .agent.md)"
    dest="$out_dir/$base.mdc"
    desc="$(field_value "$src" description)"
    code="$(posture_code "$src")"
    content="$(
      echo "---"
      echo "description: $(yaml_dq "$desc")"
      echo "alwaysApply: false"
      echo "---"
      echo
      # A Cursor rule has no tools field, so the posture would be lost entirely.
      echo "## Tool posture — \`$code\`"
      echo
      posture_note "$code"
      echo
      posture_enforcement cursor "$code"
      echo
      echo "---"
      echo
      body_of "$src"
    )"
    emit "$dest" "$content"
    count=$((count+1))
  done
  echo "  $count agents -> $out_dir/ (@-mention a rule to use it)"
  gen_skill_rules "$out_dir"
  install_skills "$DEST/.cursor/skills"
  if [[ "$DEST" == "$ROOT" ]]; then
    report_owned_orphans "$out_dir" ".mdc"
    report_owned_orphans "$DEST/.cursor/skills" "/"
  else
    install_docs "$(platform_docs_base)"
    MANIFEST="$DEST/.cursor/.agents-factory-manifest"
  fi
  echo "Note: Cursor has no native orchestrator — drive the run manually in chat, or use the"
  echo "      'routing-a-step' skill rule as the router (see PORTABILITY.md)."
}

# GitHub Copilot CLI: the agents are already in the native *.agent.md format, so we COPY
# them (no conversion). Global lives in the Copilot CLI personal dir ~/.copilot/{agents,
# skills} (overridable with COPILOT_HOME); project-level is <path>/.github/{agents,skills}.
convert_copilot() {
  local base src count=0
  if [[ "$SCOPE" == "global" ]]; then
    base="${COPILOT_HOME:-$HOME/.copilot}"
  else
    base="$DEST/.github"
    [[ "$base" != "$ROOT/.github" ]] || die "that would overwrite the source of truth ($ROOT/.github)"
  fi
  for src in "$AGENTS_SRC"/*.agent.md; do
    [[ -e "$src" ]] || continue
    emit "$base/agents/$(basename "$src")" "$(cat "$src")"
    count=$((count+1))
  done
  echo "  $count agents -> $base/agents/"
  install_skills "$base/skills"
  install_docs "$(platform_docs_base)"
  MANIFEST="$base/.agents-factory-manifest"
  echo "Done. Start a run by invoking the 'delivery-orchestrator' agent with the packet."
  echo "Note: global installs target the Copilot CLI personal dir (override with COPILOT_HOME)."
  echo "See PORTABILITY.md for the agent-to-agent invocation caveat."
}

# --- Skill-shaped targets (Codex, Hermes) --------------------------------------
# Neither platform has a per-agent definition format: both discover SKILL.md folders
# and grant tools per SESSION, not per agent. So each agent ships AS a skill, and the
# posture — which the frontmatter cannot carry, let alone enforce — is written into the
# body as prose plus the platform flag that actually enforces it.
AGENT_SKILL_MARKER="<!-- $GENERATED_BY; source .github/agents/"

gen_agents_as_skills() { # gen_agents_as_skills <out_skills_dir> <codex|hermes>
  local out_dir="$1" platform="$2"
  local count=0 src base slug desc hint code content
  for src in "$AGENTS_SRC"/*.agent.md; do
    [[ -e "$src" ]] || continue
    base="$(basename "$src" .agent.md)"
    slug="$(field_value "$src" name)"; [[ -n "$slug" ]] || slug="$base"
    desc="$(field_value "$src" description)"
    hint="$(field_value "$src" argument-hint)"
    code="$(posture_code "$src")"
    content="$(
      echo "---"
      echo "name: $slug"
      echo "description: $(yaml_dq "$desc")"
      if [[ "$platform" == "hermes" ]]; then
        echo "metadata:"
        echo "  hermes:"
        echo "    tags: [agents-factory, delivery-roster, $slug]"
      fi
      echo "---"
      echo
      echo "${AGENT_SKILL_MARKER}${base}.agent.md — do not edit here, edit the source and re-run scripts/install.sh -->"
      echo
      echo "## Tool posture — \`$code\`"
      echo
      posture_note "$code"
      echo
      posture_enforcement "$platform" "$code"
      echo
      echo "## Invocation"
      echo
      echo "Standalone (one bounded task, no run): supply \`task\` and \`target\`."
      echo "Pipeline (governed run): supply \`run_id\` and the inbound handoff."
      echo "Full semantics: \`process/agent-invocation-contract.md\`."
      if [[ -n "$hint" ]]; then
        echo
        echo "Expected inputs: $hint"
      fi
      echo
      echo "---"
      echo
      body_of "$src"
    )"
    emit "$out_dir/$slug/SKILL.md" "$content"
    count=$((count+1))
  done
  echo "  $count agents -> $out_dir/<name>/SKILL.md"
}

# A framework skill and an agent would collide if they ever shared a name — both land
# in the same skills dir. Report it rather than let one silently overwrite the other.
warn_skill_name_collisions() {
  local s name
  [[ -d "$SKILLS_SRC" ]] || return 0
  for s in "$SKILLS_SRC"/*/; do
    [[ -d "$s" ]] || continue
    name="$(basename "$s")"
    if [[ -f "$AGENTS_SRC/$name.agent.md" ]]; then
      warn "skill '$name' collides with agent '$name' — one would overwrite the other."
    fi
  done
  return 0
}

convert_skill_platform() { # convert_skill_platform <codex|hermes> <base>
  local platform="$1" base="$2"
  warn_skill_name_collisions
  gen_agents_as_skills "$base/skills" "$platform"
  install_skills "$base/skills"
  install_docs "$(platform_docs_base)"
  MANIFEST="$base/.agents-factory-manifest"
}

# OpenAI Codex CLI: no agent format, but a native skills runtime that auto-discovers
# $CODEX_HOME/skills/<name>/SKILL.md (project-level: <path>/.codex/skills).
convert_codex() {
  local base
  if [[ "$SCOPE" == "global" ]]; then base="${CODEX_HOME:-$HOME/.codex}"; else base="$DEST/.codex"; fi
  convert_skill_platform codex "$base"
  echo "Done. Codex auto-discovers $base/skills — ask for an agent by name, e.g. 'use the ux-flow-designer skill'."
  echo "Note: Codex has no agent-to-agent dispatch. Drive a run yourself in playbook order,"
  echo "      or use the routing-a-step skill as the router and paste each handoff. See PORTABILITY.md."
}

# Hermes Agent (Nous Research): same shape — no file-based agent roster, but a native
# skills runtime rooted at $HERMES_HOME/skills/<name>/SKILL.md.
convert_hermes() {
  local base
  if [[ "$SCOPE" == "global" ]]; then base="${HERMES_HOME:-$HOME/.hermes}"; else base="$DEST/.hermes"; fi
  convert_skill_platform hermes "$base"
  echo "Done. Hermes discovers $base/skills — check with 'hermes skills list'."
  if [[ "$SCOPE" != "global" ]]; then
    echo "Note: Hermes resolves skills from HERMES_HOME — run with HERMES_HOME=$base."
  fi
  echo "Note: Hermes spawns subagents by prompt, not from a roster file. The orchestrator can"
  echo "      delegate by naming the agent skill in the subagent's prompt. See PORTABILITY.md."
}

# --- Roo/Zoo custom modes (shared by the generic .agents and native roo targets) -
# VS Code tool id -> Roo Code tool group. Roo groups are coarse: read, edit, browser,
# command, mcp. "search" folds into read; "todo"/"agent"/"vscode" have no group.
map_tool_group() {
  case "$1" in
    read|search) echo "read" ;;
    edit)        echo "edit" ;;
    execute)     echo "command" ;;
    web|fetch)   echo "browser" ;;
    *)           echo "" ;;
  esac
}

roo_groups_line() { # roo_groups_line <file>
  local id mapped g seen=" " joined=""
  for id in $(tool_ids "$1"); do
    mapped="$(map_tool_group "$id")"
    [[ -n "$mapped" ]] || continue
    case "$seen" in *" $mapped "*) continue ;; esac
    seen="$seen$mapped "
  done
  for g in read edit browser command mcp; do
    case "$seen" in *" $g "*) joined="$joined, $g" ;; esac
  done
  [[ -n "$joined" ]] || joined=", read"
  echo "groups: [${joined#, }]"
}

# requirements-analyst -> "Requirements Analyst"   (awk: portable across GNU and BSD)
title_case() {
  echo "$1" | awk '{ gsub(/-/," "); for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2); print }'
}

# roo_mode <file> <key_indent> — one custom-mode mapping. Block scalars carry an explicit
# indentation indicator (|2- / |4-), so a body whose first line is indented (a code
# block, a nested list) still parses: YAML would otherwise infer the indent from it.
roo_mode() {
  local src="$1" ki="$2" base slug name desc role pad
  base="$(basename "$src" .agent.md)"
  slug="$(field_value "$src" name)"; [[ -n "$slug" ]] || slug="$base"
  name="$(title_case "$slug")"
  desc="$(field_value "$src" description)"
  role="$(persona_of "$src")"
  [[ -n "$role" ]] || role="$desc"             # fallback if no "You are" line
  pad="$(printf '%*s' "$ki" '')"
  echo "slug: $slug"
  echo "${pad}name: $name"
  echo "${pad}roleDefinition: |2-"
  printf '%s\n' "$role" | indent_block $((ki + 2))
  if [[ -n "$desc" ]]; then
    echo "${pad}whenToUse: |2-"
    printf '%s\n' "$desc" | indent_block $((ki + 2))
  fi
  echo "${pad}$(roo_groups_line "$src")"
  echo "${pad}customInstructions: |2-"
  body_of "$src" | indent_block $((ki + 2))
}

# Generic ".agents" target: one YAML file per agent, each a single Roo-style custom-mode
# object. Roo Code itself reads a single .roomodes — see the roo target below.
gen_agents_roo() {
  local out_dir="$1" count=0 src base
  for src in "$AGENTS_SRC"/*.agent.md; do
    [[ -e "$src" ]] || continue
    base="$(basename "$src" .agent.md)"
    emit "$out_dir/$base.yaml" "# $GENERATED_BY from .github/agents/$base.agent.md — do not edit
$(roo_mode "$src" 0)"
    count=$((count+1))
  done
  echo "  $count agents -> $out_dir/ (Roo Code custom-mode format)"
}

convert_agents() {
  gen_agents_roo "$DEST/.agents"
  install_skills "$DEST/.agents/skills"
  write_skills_index "$DEST/.agents/skills" \
    "Read a skill's \`SKILL.md\` and follow it as written before starting the matching task."
  install_docs "$(platform_docs_base)"
  MANIFEST="$DEST/.agents/.agents-factory-manifest"
  echo "Done. Point your harness at $DEST/.agents (one custom-mode YAML per agent)."
  echo "Note: Roo Code itself reads a single .roomodes (customModes: array) — use '--target roo'"
  echo "      for that native single-file layout. These per-agent files target generic"
  echo "      .agents-style loaders. See PORTABILITY.md."
}

# --- Native Roo Code target (single .roomodes with a customModes: array) --------
ROO_MARKER="# $GENERATED_BY"

roomodes_content() {
  local src
  echo "$ROO_MARKER — the roster as Zoo/Roo custom modes. Do not edit; re-run the installer."
  echo "customModes:"
  for src in "$AGENTS_SRC"/*.agent.md; do
    [[ -e "$src" ]] || continue
    # sequence item at 2 spaces, its keys at 4, block-scalar bodies at 6
    roo_mode "$src" 4 | awk 'NR == 1 { print "  - " $0; next } { print }'
  done
}

# write_roomodes <file> — through emit (so --dry-run/--check are honoured), refusing to
# overwrite a modes file this script did not generate: it may hold the user's own modes.
write_roomodes() {
  local out_file="$1" content
  content="$(roomodes_content)"
  local first=""
  [[ ! -f "$out_file" ]] || IFS= read -r first < "$out_file" || true
  if [[ -f "$out_file" ]] && [[ "$first" != "$ROO_MARKER"* ]]; then
    if ! $FORCE; then
      warn "$out_file exists and was not generated by this script (it may hold your own modes). Merge by hand, or re-run with --force to replace it (a .bak copy is kept)."
      note_generated "$out_file"
      SKIPPED=$((SKIPPED+1))
      return 0
    fi
    if ! $DRY_RUN; then
      cp -p "$out_file" "$out_file.bak"
      echo "  backed up $out_file -> $out_file.bak"
    fi
  fi
  emit "$out_file" "$content"
  echo "  $(grep -c '^  - slug: ' <<<"$content") agents -> $out_file (native Roo Code customModes: array)"
}

# Candidate dirs that hold the GLOBAL modes file (custom_modes.yaml). Roo Code and
# its active successor Zoo Code (the community fork; Roo was archived in 2026) both
# store global modes inside the editor's VS Code globalStorage for the extension —
# NOT in $HOME. Zoo Code keeps the same format and filenames (.roomodes,
# custom_modes.yaml, the customModes: array); only the extension id differs:
#   zoocodeorganization.zoo-code  (Zoo Code — current)
#   rooveterinaryinc.roo-cline    (Roo Code — legacy)
# The "User" dir location depends on the install: a DESKTOP editor uses an OS config
# root (<root>/<Editor>/User), while a REMOTE/SERVER editor (SSH, WSL, devcontainer,
# Codespaces, code-server) uses ~/.<editor>-server/data/User. We enumerate both,
# crossed with the two extension ids. Override the search with ROO_SETTINGS_DIR=<dir>.
roo_global_settings_dirs() {
  if [[ -n "${ROO_SETTINGS_DIR:-}" ]]; then printf '%s\n' "$ROO_SETTINGS_DIR"; return; fi
  local root e ext userdir
  local exts=("zoocodeorganization.zoo-code" "rooveterinaryinc.roo-cline")
  local userdirs=()

  # Desktop editors: <os-config-root>/<Editor>/User
  local editors=("Code" "Code - Insiders" "VSCodium" "Cursor" "Windsurf")
  case "$(uname -s)" in
    Darwin) root="$HOME/Library/Application Support" ;;
    Linux)  root="${XDG_CONFIG_HOME:-$HOME/.config}" ;;
    *)      root="${APPDATA:-$HOME/.config}" ;;            # Windows (Git Bash / MSYS)
  esac
  for e in "${editors[@]}"; do
    userdirs+=("$root/$e/User")
  done

  # Remote / server editors (VS Code Server over SSH/WSL/devcontainers/Codespaces):
  # ~/.<editor>-server/data/User — plus code-server's own layout.
  for e in .vscode-server .vscode-server-insiders .cursor-server .windsurf-server .vscodium-server; do
    userdirs+=("$HOME/$e/data/User")
  done
  userdirs+=("$HOME/.local/share/code-server/User")

  for userdir in "${userdirs[@]}"; do
    for ext in "${exts[@]}"; do
      printf '%s\n' "$userdir/globalStorage/$ext/settings"
    done
  done
}

# Write the roster into the global custom_modes.yaml for every editor that has Zoo
# Code (or legacy Roo Code) installed — i.e. whose globalStorage dir already exists.
# If none is found, fail loudly with the candidate paths rather than silently
# writing a file the extension will never read.
install_roo_global() {
  local found=0 dir ext_dir
  while IFS= read -r dir; do
    ext_dir="$(dirname "$dir")"                            # .../<extension-id>
    # ROO_SETTINGS_DIR is taken verbatim; otherwise require the extension's storage to exist.
    if [[ -n "${ROO_SETTINGS_DIR:-}" || -d "$ext_dir" ]]; then
      write_roomodes "$dir/custom_modes.yaml"
      found=$((found+1))
    fi
  done < <(roo_global_settings_dirs)

  if [[ $found -eq 0 ]]; then
    {
      echo "error: could not find Zoo Code / Roo Code global storage for any known editor."
      echo "The global modes file is custom_modes.yaml under the editor's globalStorage:"
      roo_global_settings_dirs | sed 's/^/  /'
      echo "Fixes: (1) open Zoo Code in your editor at least once so that dir exists, then re-run;"
      echo "       (2) set ROO_SETTINGS_DIR=<that settings dir> and re-run; or"
      echo "       (3) use --scope project --path <dir> to write a workspace .roomodes instead."
    } >&2
    exit 1
  fi

  install_skills "$HOME/.roo/skills"                        # no native skills runtime; staged for manual use
  write_skills_index "$HOME/.roo/skills" \
    "Read a skill's \`SKILL.md\` and follow it as written before starting the matching task."
  install_docs "$(platform_docs_base)"
  MANIFEST="$HOME/.roo/.agents-factory-manifest"
  echo "Done. Reload your editor window — the modes appear globally in Zoo Code / Roo Code."
  echo "Switch to the 'delivery-orchestrator' mode to start a run."
  echo "Skills have no native Roo runtime — staged under ~/.roo/skills for manual invoke. See PORTABILITY.md."
}

convert_roo() {
  if [[ "$SCOPE" == "global" ]]; then
    install_roo_global
    return
  fi
  write_roomodes "$DEST/.roomodes"
  install_skills "$DEST/.roo/skills"
  write_skills_index "$DEST/.roo/skills" \
    "Read a skill's \`SKILL.md\` and follow it as written before starting the matching task."
  install_docs "$(platform_docs_base)"
  MANIFEST="$DEST/.roo/.agents-factory-manifest"
  echo "Done. Roo Code reads $DEST/.roomodes natively (top-level customModes: array)."
  echo "Start a run by switching to the 'delivery-orchestrator' mode and pointing it at the packet."
  echo "Skills have no native Roo runtime — installed under $DEST/.roo/skills for manual invoke. See PORTABILITY.md."
}

# Framework docs only — what a plugin install (or any harness pointed at its own
# definitions) needs next to it.
convert_docs() {
  local base
  base="$(platform_docs_base)"
  [[ "$base" != "$ROOT/.agents-factory" ]] || die "this repository already has process/ and templates/ at its root"
  install_docs "$base"
  echo "Done. Framework docs -> $base (agents resolve process/ and templates/ from here)."
}

# `repo` regenerates every derived directory tracked in THIS repository, in one pass,
# so a single command after editing .github/ leaves nothing stale.
convert_repo() {
  echo "-- plugin components (agents/ skills/ commands/)"
  convert_plugin
  echo "-- Claude Code (.claude/)"
  convert_claude
  echo "-- Cursor (.cursor/rules/)"
  convert_cursor
}

BANNER="agents-factory install — target: $TARGET, scope: ${SCOPE:-n/a}, dest: $DEST"
if $DRY_RUN; then BANNER="$BANNER  [dry run — nothing will be written]"; fi
echo "$BANNER"
case "$TARGET" in
  claude)  convert_claude ;;
  cursor)  convert_cursor ;;
  copilot) convert_copilot ;;
  codex)   convert_codex ;;
  hermes)  convert_hermes ;;
  agents)  convert_agents ;;
  roo|zoo) convert_roo ;;
  docs)    convert_docs ;;
  plugin)  convert_plugin ;;
  repo)    convert_repo ;;
esac

report_manifest_orphans
write_manifest

WARNINGS="$(warning_count)"
if $DRY_RUN; then
  echo "Summary: $WOULD would change, $UNCHANGED unchanged, $SKIPPED skipped, $ORPHANS orphaned, $WARNINGS warnings."
else
  echo "Summary: $WROTE written, $UNCHANGED unchanged, $SKIPPED skipped, $ORPHANS orphaned, $WARNINGS warnings."
fi

# --check turns the report into a gate: a derived tree that is stale, orphaned, or
# warned about fails the build instead of quietly drifting from .github/.
if $CHECK && { [[ $WOULD -gt 0 ]] || [[ $ORPHANS -gt 0 ]] || [[ $WARNINGS -gt 0 ]]; }; then
  echo "check FAILED: derived files are out of date with .github/ — run the same command without --check." >&2
  exit 1
fi
